### ISSUE TITLE
Refactor dynamicEnv usage: Unify class variable access [3]

### ISSUE THREAD

**Issue by He3lixxx** [hpi-swa-teaching/RatPack2.0#65]
class `RPApplication`, method `postFromRequest`: accesses `self threadLocal: RPApplication requestKey` instead of using `self request` which would access `self threadLocal: self class requestKey`. This will cause bugs if you override the requestKey in a subclass. This exists in more than one place.

Also, a class comment for the reason for this variable should be added (necessary for pseudo-parallel processing of multiple requests)

**Comment by skydivin4ng3l** [comment]
In `ProcessRequest` there is a similar call: `self threadlocal: self class requestKey put: aHttpRequest`.
Should this also be refactored somehow?

**Comment by skydivin4ng3l** [comment]
```
parsedRequestContents

	^ self threadLocal: (self class parsedRequestContentsKey)
```
Should we change this?
