### ISSUE TITLE
API routes: Use parsedRequestContents instead of doing own parsing [13]

### ISSUE THREAD

**Issue by He3lixxx** [hpi-swa-teaching/RatPack2.0#74]
Follow-up to #69:

- [ ] Change all API routes to use parsedRequestContents instead of parsing the requests body.

When this is done, we can add support for more content types by just adding new content decoders (which maybe should be another issue?)

**Comment by richardebeling** [comment]
- [x] do the changes for put requests [7]
- [x] do the changes for post requests [7] (in sprint from 27.06. on)

**Comment by richardebeling** [comment]
post-part product owner approved
