### ISSUE TITLE
put changes id to string [8]

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#79]
When calling put on Model with a complete or incomplete json the id changes to string

Example:
Post: {"salary":20,"name":"Tim Tester"}
Result: {"object":{"salary":20,"name":"Tim Tester"},"metadata":{"id":1}}
Put: {"salary":20,"name":"Tim Tester"} 
Result: {"object":{"salary":20,"name":"Tim Tester"},"metadata":{"id":**"** 1 **"**}}

- [x] put doesnt change the id field

**Comment by skydivin4ng3l** [comment]
My estimation [13]

- I have an idea where to look but can not tell how long it will take to find the reason

**Comment by He3lixxx** [comment]
5 from me.

**Comment by jakobmache** [comment]
8

**Comment by tom95** [comment]
- [ ] put doesnt change the id field
