### ISSUE TITLE
put with incomplete json body change unset attributes to default values [13]

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#80]
Each model has preserves default values for each attribute. These are used properly by post.
Updating with put only a part of attributes changes the unset attributes (which should stay as they are) to the default values.
So you always have to construct the whole json if you don't want to lose data.

Example:
Post: {"salary":20,"name":"Tim Tester"}
Result: {"object":{"salary":20,"name":"Tim Tester"},"metadata":{"id":1}}
Put: {"salary":20}
Result: {"object":{"salary":20,"name":"Max Mustermann"},"metadata":{"id":"1"}}

**Comment by skydivin4ng3l** [comment]
My Estimation [8]

-based on the idea that we just have to find the correct SQL command in the documentation and implement it

**Comment by essal0815** [comment]
13
Variable SQL Statements

**Comment by He3lixxx** [comment]
8

**Comment by jakobmache** [comment]
13

**Comment by tom95** [comment]
- [ ] Put doesnt change the fields of the not defined values of json

**Comment by skydivin4ng3l** [comment]
Modify updateFromRequest:
- should use: `Self database loadModelObject: anID from: aRPModelClass` to get the object to update
- replace CreateObject with an UpdateObjectWithJson function
- UpdateObjectWithJson should just alter the fields of the loaded Object, which are contained in the jsonString.
-The initializedObjectFrom works similar but sets the deafault values, we don't want that.
