### ISSUE TITLE
Middleware Support [30 + 20]

### ISSUE THREAD

**Issue by tom95** [hpi-swa-teaching/RatPack2.0#83]
- [x] define superclass
- [x] support black- and whitelisting for specific routes
- [x] the API is easily understandable as previously discussed
- [x] changing middlewares while the app is running results in an error
- [x] middleware can read from and write into a shared environment per request
- [x] a middleware receives the environment and the next handler as arguments. It can choose not to call the next handler. The next handler can be another middleware or the route.

**Comment by He3lixxx** [comment]
approved by product owner
