### ISSUE TITLE
middleware squeak 5.0 support

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#88]
maximum 1h research
if not fixed in 1h than drop support

**Comment by skydivin4ng3l** [comment]
for me 20

**Comment by He3lixxx** [comment]
Can't investigate since travis does not build the current develop, so we can't see where it fails. The last build was 7 days ago, before the pull request introducing the failure was merged. So this needs fixing of travis first.

**Comment by richardebeling** [comment]
Problem is that Dictionary does not implement `at:ifPresent:ifAbsentPut:` in Squeak-5.0. So, if we change `RPTestMiddleware` to don't use that in `incrementPreHookCounter`, `incrementPostHookCounter` and `incrementTimer`, the tests will pass. I'll open a PR.
