### ISSUE TITLE
Make parsedRequestContents stuff a middleware [10]

### ISSUE THREAD

**Issue by He3lixxx** [hpi-swa-teaching/RatPack2.0#89]
We now have support for middleware. Make everything implemented in #69 a middleware and include it by default.

**Comment by He3lixxx** [comment]
13 from me

**Comment by jakobmache** [comment]
13

**Comment by essal0815** [comment]
13

**Comment by skydivin4ng3l** [comment]
Notes for me: All the parsing should be done in the prehook
- parsing of the body which is located in the request object which is located in the environment
- parsed contents should be placed in parsedrequest content which is located in the environment
-conetnt decoders should remein in the core but have to be accessed by the middleware mybe with settings?!

**Comment by richardebeling** [comment]
Reopened to wait for product owner approval

**Comment by richardebeling** [comment]
Product Owner Approved
