### ISSUE TITLE
Document: Blacklist, Hook and other middleware conventions

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#91]
* preHook return controls the flow
* Blacklist by regex and made for each middleware itself
   * inherit to change regex from given middleware

* ....

**Comment by Nina510** [comment]
see [https://github.com/hpi-swa-teaching/RatPack2.0/wiki/Middleware-Conventions](url)

**Comment by He3lixxx** [comment]
I rewrote some parts and I am now happy with it.

**Comment by essal0815** [comment]
@tom95 please close the issue if you as customer red the wiki entry

**Comment by tom95** [comment]
Reviewed and approved!
