### ISSUE TITLE
Parameter for middleware

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#96]
Having the possibility to define which middleware shall be used and with which parameters at one point.

Idea:
Class RPApplication globalMiddleware returns dictionary with symbol -> arguments
One Pragma per each middleware in the handler -> first issymbol and the others are arguments (not sure about implenetation)

(probable problem, execution order ?! Iterating over dictionary or more pragmas ...)

**Comment by He3lixxx** [comment]
What's the use case?

**Comment by essal0815** [comment]
Can we close the issue then ?

**Comment by richardebeling** [comment]
@Nina510 @skydivin4ng3l @jakobmache opinions?

**Comment by ninaihde** [comment]
I agree with the fact that middleware should stay stateless so I think we can close the issue.
